Repository mranv/wazuhRND, pull requests merged in 2024-07, with the labels that each got.

#3 Add: Auto-logging for faster and efficient debugging.
  debug/autoLog.py
  debug/config.py
  var/osssec/logs/.gitkeep
Labels: good first issue

#4 Set the Logger in Verbous mode
  framework/wazuh/active_response.py
  framework/wazuh/core/active_response.py
  framework/wazuh/core/custom_logger.py
  framework/wazuh/core/wazuh_queue.py
Labels: logger

#7 update the agent iteration to ascync iteration
  framework/wazuh/active_response.py
Labels: logger, async

#9 solve some syntax error
  framework/wazuh/core/wazuh_queue.py
Labels: dependencies, logger
